---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: plex
spec:
  rules:
    - host: {{ .Values.hostname }}
      http:
        paths:
          - backend:
              serviceName: plex
              servicePort: 32400
