---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: nextcloud
spec:
  rules:
    - host: {{ .Values.hostname }}
      http:
        paths:
          - backend:
              serviceName: nextcloud
              servicePort: 80
