---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: transmission
spec:
  rules:
    - host: {{ .Values.hostname }}
      http:
        paths:
          - backend:
              serviceName: transmission
              servicePort: 9091
